# Generated by Django 5.1.4 on 2025-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage_threshold', models.FloatField(default=80.0)),
                ('ram_usage_threshold', models.FloatField(default=8.0)),
                ('disk_usage_threshold', models.FloatField(default=10.0)),
                ('uptime_threshold', models.FloatField(default=24.0)),
                ('temperature_threshold', models.FloatField(default=75.0)),
            ],
        ),
    ]
